train:
  batch_size: 32
  num_workers: 16
  datasets:
    - _target_: source.datasets.classic.LibrispeechDataset
      part: dev-other
      max_audio_length: 17.0
      max_text_length: 270
      text_encoder: source.text_encoder.ctc_char_text_encoder.CTCCharTextEncoder
      wave_augs:
        - _target_: source.augmentations.wave_augmentations.Gain
          p: 0.7
        - _target_: source.augmentations.wave_augmentations.AddColoredNoise
          p: 0.5
        - _target_: source.augmentations.wave_augmentations.PitchShift
          p: 0.5
      spec_augs:
        - _target_: source.augmentations.spectrogram_augmentations.TimeStretch
          p: 0.3
          min_coef: 0.8
          max_coef: 1.2

    - _target_: source.datasets.classic.LibrispeechDataset
      part: train-other-500
      max_audio_length: 17.0
      max_text_length: 270
      text_encoder: source.text_encoder.ctc_char_text_encoder.CTCCharTextEncoder
      wave_augs:
        - _target_: source.augmentations.wave_augmentations.Gain
          p: 0.7
        - _target_: source.augmentations.wave_augmentations.AddColoredNoise
          p: 0.5
        - _target_: source.augmentations.wave_augmentations.PitchShift
          p: 0.5
      spec_augs:
        - _target_: source.augmentations.spectrogram_augmentations.TimeStretch
          p: 0.3
          min_coef: 0.8
          max_coef: 1.2


test:
  batch_size: 16
  num_workers: 16
  datasets:
    - _target_: source.datasets.classic.LibrispeechDataset
      part: test-other
      limit: 1500