filepath:

separate_audio:
  filepath:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/video_n_audio_separated"

bsrnn:
  n_gpu: 1
  model: "/home/comp/Рабочий стол/AutoDub/source/configs/bsrnn/arch/model_conf.yaml"
  sr: 44100
  filepath:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/bsrnn"
  checkpoint_path: "/home/comp/Рабочий стол/AutoDub/checkpoints/bsrnn/main.pth"
  window_type: "hann"
  chunk_size_second: 6.0
  hop_size_second: 0.5
  batch_size: 6

vad:
  sr: 16000
  filepath:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/vad"
  checkpoint_path: "/home/comp/Рабочий стол/AutoDub/checkpoints/vad"
  activation_th: 0.8
  deactivation_th: 0.0
  close_th: 0.250
  len_th: 0.250

#asr:
#  type: "ds2"
#  n_gpu: 1
#  model: "/home/comp/Рабочий стол/AutoDub/source/configs/asr/arch/model_conf.yaml"
#  sr: 16000
#  filepath:
#  boundaries:
#  output_dir: "/home/comp/Рабочий стол/AutoDub/output/asr"
#  checkpoint_path: "/home/comp/Рабочий стол/AutoDub/checkpoints/asr/main.pth"

asr:
  type: "whisper"
  model: "/home/comp/Рабочий стол/AutoDub/source/configs/asr/arch/model_conf.yaml"
  sr: 16000
  filepath:
  boundaries:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/asr"
  checkpoint_path: "/home/comp/Рабочий стол/AutoDub/checkpoints/asr/main.pth"
  
tr:
  filepath:
  output_dir : "/home/comp/Рабочий стол/AutoDub/output/translated/"

cut:
  filepath:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/cutted/"
  csv_filepath:

tts:
  csv_filepath: 
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/tts"
  filename: 
  target_sr: 
  checkpoint_path: "/home/comp/Рабочий стол/AutoDub/checkpoints/tts/lazy"

align_audio:
  csv_filepath:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/aligned_audio"
  filename:

concatenate:
  speech_path:
  background_path:
  csv_filepath:
  filename:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/final"
  join_video: False
  video_path: ""