bsrnn:
  n_gpu: 1
  model: "/home/comp/Рабочий стол/AutoDub/source/configs/bsrnn/arch/model_conf.yaml"
  sr: 44100
  filepath:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/bsrnn"
  checkpoint_path: "/home/comp/Рабочий стол/AutoDub/checkpoints/bsrnn/main.pth"
  window_type: "hann"
  chunk_size_second: 6.0
  hop_size_second: 0.5
  batch_size: 6

vad:
  sr: 16000
  filepath:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/vad"
  checkpoint_path: "/home/comp/Рабочий стол/AutoDub/checkpoints/vad"
  activation_th: 0.8
  deactivation_th: 0.0
  close_th: 0.250
  len_th: 0.250

asr:
  n_gpu: 1
  model: "/home/comp/Рабочий стол/AutoDub/source/configs/asr/arch/model_conf.yaml"
  sr: 16000
  filepath:
  boundaries:
  output_dir: "/home/comp/Рабочий стол/AutoDub/output/asr"
  checkpoint_path: "/home/comp/Рабочий стол/AutoDub/checkpoints/asr/main.pth"
  
tr:
  filepath:
  output_dir : "/home/comp/Рабочий стол/AutoDub/output/translated/"