filepath: "$ROOT/input/test2.mp4"

separate_audio:
  filepath:
  output_dir: "$ROOT/output/video_n_audio_separated"

bsrnn:
  n_gpu: 1
  model: "$ROOT/source/configs/bsrnn/arch/model_conf.yaml"
  sr: 44100
  filepath:
  output_dir: "$ROOT/output/bsrnn"
  checkpoint_path: "$ROOT/checkpoints/bsrnn/main.pth"
  window_type: "hann"
  chunk_size_second: 6.0
  hop_size_second: 0.5
  batch_size: 4
  use_fader: False
  max_len: 5.0

asr_wtime:
  model: "small.en"
  sr: 16000
  filepath:
  output_dir: "$ROOT/output/asr"
  checkpoint_path: "$ROOT/checkpoints/asr/whisper"

diarize:
  audio_filepath: "$ROOT/output/asr/test2_audio_mono_speech_resampled/test2_audio_mono_speech_resampled.wav"
  csv_filepath: "$ROOT/output/asr/test2_audio_mono_speech_resampled/test2_audio_mono_speech_resampled_asr.csv"
  output_dir: "$ROOT/output/label"
  cluster_type: "dbscan"
  cluster_cfg:
    metric: "cosine"
    eps: 0.75
    min_samples: 1
  
tr:
  filepath:
  output_dir : "$ROOT/output/translated/"
  use: "opusmt"
  checkpoint_path: "$ROOT/checkpoints/translate/opusmt"

cut:
  filepath:
  output_dir: "$ROOT/output/cutted/"
  csv_filepath:
  save_segments: True
  save_common: True

tts:
  csv_filepath: 
  output_dir: "$ROOT/output/tts"
  filename: 
  target_sr: 
  checkpoint_path: "$ROOT/checkpoints/tts/lazy"

align_audio:
  csv_filepath:
  output_dir: "$ROOT/output/aligned_audio"
  filename:

concatenate:
  speech_path:
  background_path:
  csv_filepath:
  filename:
  output_dir: "$ROOT/output/final"
  join_video: False
  video_path: ""