defaults:
  - arch: model_conf
n_gpu: 1
paths:
 input: "/home/comp/Рабочий стол/AutoDub/input/changed.wav"
 #input: "/home/comp/Рабочий стол/AutoDub/input/2.flac"
 boundaries: "/home/comp/Рабочий стол/AutoDub/input/vad_result.txt"
 output: "/home/comp/Рабочий стол/AutoDub/output/asr/"
 checkpoint: "/home/comp/Рабочий стол/AutoDub/checkpoints/asr/main.pth"
